Projekt/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Mvc;
using Projekt.Models.AssignmentTruck;
using Projekt.Services.Truck;
using Projekt.Services.AssignmentTruck;
using Projekt.Services.User;
using System.IO;

namespace Projekt.Controllers
{
    public class AssignmentController : Controller
    {
        private readonly IAssignmentService _assignmentService;
        private readonly ITruckService _filmService;
        private readonly IUserService _userService;



        public AssignmentController(IAssignmentService assignmentService, ITruckService filmService, IUserService userService)
        {
            _assignmentService = assignmentService;
            _filmService = filmService;
            _userService = userService;
        }


        public IActionResult Index()
        {
            var model = new AssignmentViewModel()
            {
                AssignmentTrucks = _assignmentService.GetAssignments(),
                Trucks = _filmService.GetTrucks(),
                Users = _userService.GetUsers()
            };
            return View(model);
        }


        public IActionResult AssignmentTrucks()
        {
            var model = new AssignmentViewModel()
            {
                AssignmentTrucks = _assignmentService.GetAssignments(),
                Trucks = _filmService.GetTrucks(),
                Users = _userService.GetUsers()
            };
            return View(model);
        }
        
        public IActionResult AssignmentThisTruck(int truckId, int userId)
        {
            if (truckId != 0 && userId != 0)
            {
                _assignmentService.AssignmentTruck(truckId, userId);
                return RedirectToAction("Index");
            }

        TempData["message"] = "Popraw dane.";
        return RedirectToAction("Index");
        }

        public IActionResult DeleteAssignment()
        {
            var model = new AssignmentViewModel()
            {
                AssignmentTrucks = _assignmentService.GetAssignments(),
                Trucks = _filmService.GetTrucks(),
                Users = _userService.GetUsers()
            };
            return View(model);
        }

        public IActionResult DeleteThisAssignment(int id)
        {
            var items = _assignmentService.GetAssignments().Count();
            if(id != 0)
            {
                _assignmentService.DeleteAssignment(id);
                return RedirectToAction("Index");
            }

        TempData["message"] = "Popraw dane.";
        return RedirectToAction("Index");
        }

        public IActionResult ReturnAssignment()
        {
            var model = new AssignmentViewModel()
            {
                AssignmentTrucks = _assignmentService.GetAssignments(),
                Trucks = _filmService.GetTrucks(),
                Users = _userService.GetUsers()
            };

            return View(model);
        }

        public IActionResult ReturnThisAssignment(int id)
        {
            if (id != 0 )
            {
                _assignmentService.ReturnAssignment(id);
                return RedirectToAction("Index");
            }
            TempData["message"] = "Popraw dane.";
            return RedirectToAction("Index");
        }
    }
}

Projekt/Controllers/TrailersController.cs
using Microsoft.AspNetCore.Mvc;
using Projekt.Models.Trailer;
using Projekt.Services.Trailer;

namespace Projekt.Controllers
{
    public class TrailersController : Controller
    {
        private readonly ITrailerService _trailerService;
        public TrailersController(ILogger<TrailersController> logger, ITrailerService trailerService)
        {
            _trailerService = trailerService;
        }

        public IActionResult Index()
        {
            var model = new TrailerViewModel()
            {
                Trailers = _trailerService.GetTrailer()
            };
            return View(model);
        }

        public IActionResult InsertNewTrailer()
        {
            return View();
        }


        public IActionResult InsertTrailer(string Model, string Brand, string Type, int MaxLoad, int YearOfProduction)
        {
            if (string.IsNullOrEmpty(Model) && string.IsNullOrEmpty(Brand) && string.IsNullOrEmpty(Type) && MaxLoad == 0 && YearOfProduction == 0)
            {
                TempData["message"] = "Popraw dane.";
                return RedirectToAction("Index");
            }
            _trailerService.InsertTrailer(Model, Brand, Type, MaxLoad, YearOfProduction);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteTrailer()
        {
            var model = new TrailerViewModel()
            {
                Trailers = _trailerService.GetTrailer()
            };
            return View(model);
        }

        public IActionResult DeleteThisTrailer(int id)
        {
            if (id != 0)
            {
                _trailerService.DeleteTrailer(id);
                return RedirectToAction("Index");
            }
            TempData["message"] = "Popraw dane.";
            return RedirectToAction("Index");
        }

        public IActionResult UpdateTrailer()
        {
            var model = new TrailerViewModel()
            {
                Trailers = _trailerService.GetTrailer()
            };
            return View(model);
        }

        public IActionResult UpdateThisTrailer(int id, string Model, string Brand, string Type, int MaxLoad, int YearOfProduction)
        {
            var items = _trailerService.GetTrailer().Count();
            if (id != 0 && Model != "" && Type != "" && MaxLoad != 0 && YearOfProduction != 0)
            {
                _trailerService.UpdateTrailer(id, Model, Brand, Type, MaxLoad, YearOfProduction);
                return RedirectToAction("Index");
            }
            TempData["message"] = "Popraw dane.";
            return RedirectToAction("Index");
        }
    }
}

Projekt/Controllers/TrucksController.cs
using Microsoft.AspNetCore.Mvc;
using Projekt.Models.Trucks;
using Projekt.Services.Truck;

namespace Projekt.Controllers
{
    public class TrucksController : Controller
    {
        private readonly ITruckService _truckService;
        public TrucksController(ILogger<TrucksController> logger, ITruckService truckService)
        {
            _truckService = truckService;
        }

        public IActionResult Index()
        {
            var model = new TrucksViewModel()
            {
                Trucks = _truckService.GetTrucks()
            };
            return View(model);
        }

        public IActionResult InsertNewTruck()
        {
            return View();
        }

        public IActionResult InsertTruck(string Model, string Brand, int Power, int Distance, int YearOfProduction)
        {
            if(string.IsNullOrEmpty(Model) && string.IsNullOrEmpty(Brand) && Power == 0 && Distance == 0 && YearOfProduction == 0)
            {
                TempData["message"] = "Popraw dane.";
                return RedirectToAction("Index");
            }
            _truckService.InsertTruck(Model, Brand, Power, Distance, YearOfProduction);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteTruck()
        {
            var model = new TrucksViewModel()
            {
                Trucks = _truckService.GetTrucks()
            };
            return View(model);
        }


        public IActionResult DeleteThisTruck(int id)
        {
            if(id!=0)
            {
                _truckService.DeleteTruck(id);
                return RedirectToAction("Index");
            }
            TempData["message"] = "Popraw dane.";
            return RedirectToAction("Index");
        }


        public IActionResult UpDateTruck()
        {
            var model = new TrucksViewModel()
            {
                Trucks = _truckService.GetTrucks()
            };
            return View(model);
        }

        public IActionResult UpDateThisTruck(int id, string Model, string Brand, int Power, int Distance, int YearOfProduction)
        {
            var items = _truckService.GetTrucks().Count();
            if (id != 0 && Model != "" && Brand != "" && Power != 0 && Distance != 0 && YearOfProduction != 0)
            {
                _truckService.UpDateTruck(id, Model, Brand, Power, Distance, YearOfProduction);
                return RedirectToAction("Index");
            }
            TempData["message"] = "Popraw dane.";
            return RedirectToAction("Index");
        }
    }
}

Projekt/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Projekt.Models.Users;
using Projekt.Services.User;

namespace Projekt.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService _userService;

        public UsersController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index()
        {
            var model = new UserViewModel()
            {
                Users = _userService.GetUsers()
            };
            return View(model);
        }

        public IActionResult CreateUser()
        {
            return View();
        }

        public IActionResult SendUser(string FirstName, string LastName, string Email)
        {
            if(string.IsNullOrEmpty(FirstName) && string.IsNullOrEmpty(LastName) && string.IsNullOrEmpty(Email))
            {
                TempData["message"] = "Popraw dane.";
                return RedirectToAction("Index");
            }
            _userService.CreateUser(FirstName, LastName, Email);
            return RedirectToAction("Index");
        }

        public IActionResult UpDateUser()
        {
            var model = new UserViewModel()
            {
                Users = _userService.GetUsers()
            };
            return View(model);
        }

        public IActionResult UpDateThisUser(int id, string FirstName, string LastName, string Email)
        {
            var item = _userService.GetUsers().Count();
            if (id == 0 && id < item && string.IsNullOrEmpty(FirstName) && string.IsNullOrEmpty(LastName) && string.IsNullOrEmpty(Email))
            {
                TempData["message"] = "Popraw dane.";
                return RedirectToAction("Index");
            }
            _userService.UpDateUser(id, FirstName, LastName, Email);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteUser()
        {
            var model = new UserViewModel()
            {
                Users = _userService.GetUsers()
            };
            return View(model);
        }

        public IActionResult DeleteThisUser(int id)
        {
            var items = _userService.GetUsers().Count();
            if(id != 0)
            {
                _userService.DeleteUser(id);
                return RedirectToAction("Index");
            }
            TempData["message"] = "Popraw dane.";
            return RedirectToAction("Index");
        }
    }
}

Projekt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wypożyczalnia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projekt.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Zarządzanie firmą spedycyjną</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trucks" asp-action="Index">Ciężarówki</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trailers" asp-action="Index">Przyczepy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Użytkownicy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Assignment" asp-action="Index">Przypisania ciężarówek</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AssignmentTrailers" asp-action="Index">Przypisania przyczep</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Projekt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>