Projekt/Controllers/AssignmentTrailersController.cs
using Microsoft.AspNetCore.Mvc;
using Projekt.Models.AssignmentTruck;
using Projekt.Models.AssignTrailerToTruck;
using Projekt.Services.AssignmentTruck;
using Projekt.Services.AssignTrailerToTruck;
using Projekt.Services.Trailer;
using Projekt.Services.Truck;

namespace Projekt.Controllers
{
    public class AssignmentTrailersController : Controller
    {
        private readonly IAssignTrailerToTruckService _assignmentTruckService;
        private readonly ITruckService _truckService;
        private readonly ITrailerService _trailerService;



        public AssignmentTrailersController(IAssignTrailerToTruckService assignmentTrailerService, ITruckService truckService, ITrailerService trailerService)
        {
            _assignmentTruckService = assignmentTrailerService;
            _truckService = truckService;
            _trailerService = trailerService;
        }


        public IActionResult Index()
        {
            var model = new AssignTrailerToTruckViewModel()
            {
                AssignmentTrailers = _assignmentTruckService.GetAssignTrailers(),
                Trucks = _truckService.GetTrucks(),
                Trailers = _trailerService.GetTrailer()
            };
            return View(model);
        }


        public IActionResult AssignTrailer()
        {
            var model = new AssignTrailerToTruckViewModel()
            {
                AssignmentTrailers = _assignmentTruckService.GetAssignTrailers(),
                Trucks = _truckService.GetTrucks(),
                Trailers = _trailerService.GetTrailer()
            };
            return View(model);
        }

        public IActionResult AssignThisTrailer(int truckId, int trailerId)
        {
            if (truckId != 0 && trailerId != 0)
            {
                _assignmentTruckService.AssignTrailerToTruck(truckId, trailerId);
                return RedirectToAction("Index");
            }

            TempData["message"] = "Popraw dane.";
            return RedirectToAction("Index");
        }

        public IActionResult DeleteAssignTrailer()
        {
            var model = new AssignTrailerToTruckViewModel()
            {
                AssignmentTrailers = _assignmentTruckService.GetAssignTrailers(),
                Trucks = _truckService.GetTrucks(),
                Trailers = _trailerService.GetTrailer()
            };
            return View(model);
        }

        public IActionResult DeleteThisAssignTrailer(int id)
        {
            var items = _assignmentTruckService.GetAssignTrailers().Count();
            if (id != 0)
            {
                _assignmentTruckService.DeleteAssignTrailer(id);
                return RedirectToAction("Index");
            }

            TempData["message"] = "Popraw dane.";
            return RedirectToAction("Index");
        }

        public IActionResult ReturnAssignTrailer()
        {
            var model = new AssignTrailerToTruckViewModel()
            {
                AssignmentTrailers = _assignmentTruckService.GetAssignTrailers(),
                Trucks = _truckService.GetTrucks(),
                Trailers = _trailerService.GetTrailer()
            };

            return View(model);
        }

        public IActionResult ReturnThisAssignTrailer(int id)
        {
            if (id != 0)
            {
                _assignmentTruckService.ReturnAssignTrailer(id);
                return RedirectToAction("Index");
            }
            TempData["message"] = "Popraw dane.";
            return RedirectToAction("Index");
        }
    }
}

Projekt/Views/AssignmentTrailers/AssignTrailer.cshtml
@model Projekt.Models.AssignTrailerToTruck.AssignTrailerToTruckViewModel
@{
    ViewData["Title"] = "Przypisz przyczepę do ciężarówki";
}
<div class="text-center">
    <h1 class="display-4">Przypisz ciężarówkę</h1>
    <p>Wybierz ID ciężarówki którą chcesz przypisać, a następnie przyczepę</p>
</div>
<div class="text-center d-flex mb-5">
    <table class="table table-hover m-2">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Model</th>
                <th scope="col">Przypisana</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Trailers)
            {
                    <tr>
                    <td scope="row">@item.Id</td>
                    <td scope="row">@item.Model</td>
                    <td scope="row">@item.IsAssigned</td>
                </tr>
            }
        </tbody>
    </table>
    <table class="table table-hover m-2">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Model</th>
                <th scope="col">Przypisana</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Trucks)
            {
                <tr>
                    <td scope="row">@item.Id</td>
                    <td scope="row">@item.Model</td>
                    <td scope="row">@item.IsAssignedTrailer</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<form method="post" asp-controller="AssignmentTrailers" asp-action="AssignThisTrailer">
    <div class="form-group">
        <label for="Id">ID przyczepy: <span style="color:red">*</span></label>
        <input type="number" class="form-control" id="Id" placeholder="ID przyczepy" name="trailerId">
    </div>
    <div class="form-group">
        <label for="Id">ID ciężarówki: <span style="color:red">*</span></label>
        <input type="number" class="form-control" id="Id" placeholder="ID ciężarówki" name="truckId">
    </div>

    <div class="text-center m-5">
        <button type="submit" class="btn btn-success">Przypisz</button>
        <a class="btn btn-danger" href="javascript: history.go(-1)">Wróć</a>
    </div>
</form>

Projekt/Views/AssignmentTrailers/DeleteAssignTrailer.cshtml
@model Projekt.Models.AssignTrailerToTruck.AssignTrailerToTruckViewModel
@{
    ViewData["Title"] = "Usuń przypisanie przyczepy";
}
<div class="text-center">
    <h1 class="display-4">Lista przypisań</h1>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Model Ciężarówki</th>
                <th scope="col">Model przyczepy</th>
                <th scope="col">Data przypisania</th>
                <th scope="col">Data zwrotu</th>
                <th scope="col">Czy zwrócono?</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.AssignmentTrailers)
            {
                <tr>
                    <td scope="row">@item.Id</td>
                    <td scope="row">@item.Truck.Model</td>
                    <td scope="row">@item.Trailer.Model</td>
                    <td scope="row">@item.AssignmentDate.ToShortDateString()</td>
                    <td scope="row">@item.ReturnDate.ToShortDateString()</td>
                    <td scope="row">@(item.IsReturned ? "Zwrócono" : "Nie zwrócono")</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<form method="delete" asp-controller="AssignmentTrailers" asp-action="DeleteThisAssignTrailer">
    <div class="form-group">
        <label for="Id">ID przypisania: <span style="color:red">*</span></label>
        <input type="number" class="form-control" id="Id" placeholder="ID przypisania" name="Id">
    </div>

    <div class="text-center m-5">
        <button type="submit" class="btn btn-warning">Anuluj przypisanie</button>
        <a class="btn btn-danger" href="javascript: history.go(-1)">Wróć</a>
    </div>
</form>

Projekt/Views/AssignmentTrailers/Index.cshtml
@model Projekt.Models.AssignTrailerToTruck.AssignTrailerToTruckViewModel
@{
    ViewData["Title"] = "Lista przypisań przyczep do ciężarówek";
}
@if (TempData["message"] != null)
{
    <script>
        alert('@TempData["message"]');
    </script>
}
<div class="text-center">
    <h1 class="display-4">Lista przypisań przyczep do ciężarówek</h1>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Model przyczepy</th>
                <th scope="col">Model ciężarówki</th>
                <th scope="col">Data przypisania</th>
                <th scope="col">Data zwrotu</th>
                <th scope="col">Czy zwrócono?</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.AssignmentTrailers)
            {
                <tr>
                    <td scope="row">@item.Id</td>
                    <td scope="row">@item.Trailer.Id</td>
                    <td scope="row">@item.Truck.Id</td>
                    <td scope="row">@item.AssignmentDate.ToShortDateString()</td>
                    <td scope="row">@item.ReturnDate.ToShortDateString()</td>
                    <td scope="row">@(item.IsReturned ? "Zwrócono" : "Nie zwrócono")</td>
                </tr>
            }
        </tbody>
    </table>
    <div class="text-center m-5">
        <a class="btn btn-outline-success" asp-area="" asp-controller="AssignmentTrailers" asp-action="AssignTrailer" role="button">Przypisz</a>
        <a class="btn btn-outline-warning" asp-area="" asp-controller="AssignmentTrailers" asp-action="DeleteAssignTrailer" role="button">Anuluj przypisanie</a>
        <a class="btn btn-outline-danger" asp-area="" asp-controller="AssignmentTrailers" asp-action="ReturnAssignTrailer" role="button">Zwróć przyczepę</a>
    </div>
</div>

Projekt/Views/AssignmentTrailers/ReturnAssignTrailer.cshtml
@model Projekt.Models.AssignTrailerToTruck.AssignTrailerToTruckViewModel
@{
    ViewData["Title"] = "Zwróć przyczepę";
}
@if (TempData["message"] != null)
{
    <script>
        alert('@TempData["message"]');
    </script>
}
<div class="text-center">
    <h1 class="display-4">Lista przypisań</h1>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Model przyczepy</th>
                <th scope="col">Model ciężarówki</th>
                <th scope="col">Data przypisania</th>
                <th scope="col">Data zwrotu</th>
                <th scope="col">Czy zwrócono?</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.AssignmentTrailers)
            {
                <tr>
                    <td scope="row">@item.Id</td>
                    <td scope="row">@item.Trailer.Id</td>
                    <td scope="row">@item.Truck.Id</td>
                    <td scope="row">@item.AssignmentDate.ToShortDateString()</td>
                    <td scope="row">@item.ReturnDate.ToShortDateString()</td>
                    <td scope="row">@(item.IsReturned ? "Zwrócono" : "Nie zwrócono")</td>
                </tr>
            }
        </tbody>
    </table>
</div>
<form method="post" asp-controller="AssignmentTrailers" asp-action="ReturnThisAssignTrailer">
    <div class="form-group">
        <label for="Id">ID przypisania: <span style="color:red">*</span></label>
        <input type="number" class="form-control" id="Id" placeholder="ID przypisania" name="Id">
    </div>
    <div class="text-center m-5">
        <button type="submit" class="btn btn-success">Zwróć</button>
        <a class="btn btn-danger" href="javascript: history.go(-1)">Wróć</a>
    </div>
</form>